backend:
  name: git-gateway
  branch: master
media_folder: 'assets'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
