backend:
  name: git-gateway
  branch: master
media_folder: 'assets'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
      - { name: Excerpt }
      - { name: Draft }
